GOCC=go
BIN="./build/retrieval-success-rate"
GIT_SUBM=git submodule

build: 
	$(GOCC) build -o $(BIN)
install: 
	$(GOCC) install 
dependencies: 
	$(GIT_SUBM) update --init
	cd go-libp2p-kad-dht && git checkout origin/ProvidersFile